Update to use builtin patcher

diff --git a/iosas/tools/patchscript b/iosas/tools/patchscript
--- a/iosas/tools/patchscript
+++ b/iosas/tools/patchscript
@@ -1,14 +1,17 @@
 #!/bin/bash
-# Set GAMEDIR to the current directory
+# Set GAMEDIR to the current directory and set logfile
 GAMEDIR="$PWD"
+LOGFILE="$GAMEDIR/patchlog.txt"
 
+# Redirect output and error to the log file
+exec > >(tee -a "$LOGFILE") 2>&1
 echo "GAMEDIR is set to: $GAMEDIR"
 
 # Exports
-export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
 export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export TOOLDIR="$GAMEDIR/tools"
 export TMPDIR="$GAMEDIR/tmp"
+export PATH="$GAMEDIR/tools:$PATH"
 
 # Permissions
 chmod 666 /dev/uinput
@@ -30,26 +33,39 @@ process_game() {
         rm -rf gamedata
         echo "Removed gamedata directory."
         sleep 1
-    else
-        echo "gamedata directory not found. Skipping asset copy."
     fi
-    
+        
     # Check if the data.win file exists and apply xdelta
     if [ -f "data.win" ]; then
         echo "Applying xdelta patch"
-        ./tools/xdelta3 -d -s "data.win" -f "./tools/patches/idol_sfx.xdelta" "game.droid" && rm "data.win"
+        output=$(xdelta3 -d -s "data.win" -f "./tools/patches/idol_sfx.xdelta" "game.droid" 2>&1)
+        if [ $? -eq 0 ]; then
+            echo "Patch applied successfully"
+            echo "$output"
+            rm "data.win"
+        else
+            echo "Failed to apply patch"
+            echo "$output"
+            exit 1
+        fi
     fi
-    
-    # Compress audio
-    if [ -f "compress.txt" ]; then
-        echo "Compressing audio"
         
-        mkdir -p "$TMPDIR"
+    sleep 3
+    
+    #compress_audio
+	
+    # Final completion message
+    echo "Patching process complete!"
+}
 
+compress_audio() {
+    # Compress audio
+        echo "Compressing audio. The process will take 5-10 minutes."     
+        mkdir -p "$TMPDIR"
         # Run the compression tool
         echo "Running gmKtool.py with parameters..."
         PYTHON=$(which python3)
-        $PYTHON ./tools/gmKtool.py -vvv -m 1000 -b 64 -d "$TMPDIR" "$GAMEDIR/game.droid"
+        $PYTHON ./tools/gmKtool.py -vvv -m 1024 -b 64 -d "$TMPDIR" "$GAMEDIR/game.droid"
 
         if [ $? -eq 0 ]; then
             echo "Compression completed successfully."
@@ -65,20 +81,6 @@ process_game() {
             echo "Cleaning up temporary directory $TMPDIR."
             rm -rf "$TMPDIR"
         fi
-    else
-        echo "compress.txt not found. Skipping audio compression."
-    fi
-
-    sleep 3
-    
-    # Font replacements
-    if [ -f "localization_fonts.csv" ]; then
-        sed -i 's/malgun\.ttf/BMDOHYEON_ttf.ttf/g' localization_fonts.csv # Korean
-        echo "Patched font files"
-    fi
-	
-    # Final completion message
-    echo "Patching process complete!"
 }
 
 # Call the function
